/*
 * Tweek
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManifestApi
 */
@Ignore
public class ManifestApiTest {

    private final ManifestApi api = new ManifestApi();

    
    /**
     * 
     *
     * Get Manifests
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getManifestsTest() throws ApiException {
        List<Object> response = api.getManifests();

        // TODO: test validations
    }
    
}
