/* 
 * Tweek
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppCreationResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppCreationResponseModelTests
    {
        // TODO uncomment below to declare an instance variable for AppCreationResponseModel
        //private AppCreationResponseModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppCreationResponseModel
            //instance = new AppCreationResponseModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppCreationResponseModel
        /// </summary>
        [Test]
        public void AppCreationResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppCreationResponseModel
            //Assert.IsInstanceOfType<AppCreationResponseModel> (instance, "variable 'instance' is a AppCreationResponseModel");
        }


        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Test]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'AppSecret'
        /// </summary>
        [Test]
        public void AppSecretTest()
        {
            // TODO unit test for the property 'AppSecret'
        }

    }

}
