/*
 * Tweek
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KeyUpdateModel
 */
public class KeyUpdateModelTest {
    private final KeyUpdateModel model = new KeyUpdateModel();

    /**
     * Model tests for KeyUpdateModel
     */
    @Test
    public void testKeyUpdateModel() {
        // TODO: test KeyUpdateModel
    }

    /**
     * Test the property 'implementation'
     */
    @Test
    public void implementationTest() {
        // TODO: test implementation
    }

    /**
     * Test the property 'manifest'
     */
    @Test
    public void manifestTest() {
        // TODO: test manifest
    }

}
