/*
 * Tweek
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class PolicyApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get Policies</remarks>
        /// <response code="200">Ok</response>
        [HttpGet]
        [Route("/api/v2/policies")]
        [ValidateModelState]
        [SwaggerOperation("GetPolicies")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Object>), description: "Ok")]
        public virtual IActionResult GetPolicies()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Object>));

            string exampleJson = null;
            exampleJson = "\"{}\"";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Object>>(exampleJson)
            : default(List<Object>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Replace Policy</remarks>
        /// <response code="200">OK</response>
        [HttpPut]
        [Route("/api/v2/policies")]
        [ValidateModelState]
        [SwaggerOperation("ReplacePolicy")]
        public virtual IActionResult ReplacePolicy()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);


            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Update Policy</remarks>
        /// <param name="patchOperation"></param>
        /// <response code="200">OK</response>
        [HttpPatch]
        [Route("/api/v2/policies")]
        [ValidateModelState]
        [SwaggerOperation("UpdatePolicy")]
        public virtual IActionResult UpdatePolicy([FromBody]List<PatchOperation> patchOperation)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);


            throw new NotImplementedException();
        }
    }
}
