/*
 * Tweek
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class SchemaApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Delete Schema</remarks>
        /// <param name="identityType">The type of the identity</param>
        /// <param name="authorName"></param>
        /// <param name="authorEmail"></param>
        /// <response code="200">Ok</response>
        [HttpDelete]
        [Route("/api/v2/schemas/{identityType}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteIdentity")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Ok")]
        public virtual IActionResult DeleteIdentity([FromRoute][Required]string identityType, [FromQuery][Required()]string authorName, [FromQuery][Required()]string authorEmail)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));

            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default(string);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get query</remarks>
        /// <response code="200">Ok</response>
        [HttpGet]
        [Route("/api/v2/schemas")]
        [ValidateModelState]
        [SwaggerOperation("GetSchemas")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Object>), description: "Ok")]
        public virtual IActionResult GetSchemas()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Object>));

            string exampleJson = null;
            exampleJson = "\"{}\"";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Object>>(exampleJson)
            : default(List<Object>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Add identity</remarks>
        /// <param name="identityType"></param>
        /// <param name="authorName"></param>
        /// <param name="authorEmail"></param>
        /// <param name="body"></param>
        /// <response code="200">Ok</response>
        [HttpPost]
        [Route("/api/v2/schemas/{identityType}")]
        [ValidateModelState]
        [SwaggerOperation("SchemaAddIdentity")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Ok")]
        public virtual IActionResult SchemaAddIdentity([FromRoute][Required]string identityType, [FromQuery][Required()]string authorName, [FromQuery][Required()]string authorEmail, [FromBody]Object body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));

            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default(string);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Update identity</remarks>
        /// <param name="identityType"></param>
        /// <param name="authorName"></param>
        /// <param name="authorEmail"></param>
        /// <param name="patchOperation"></param>
        /// <response code="200">Ok</response>
        [HttpPatch]
        [Route("/api/v2/schemas/{identityType}")]
        [ValidateModelState]
        [SwaggerOperation("SchemaPatchIdentity")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "Ok")]
        public virtual IActionResult SchemaPatchIdentity([FromRoute][Required]string identityType, [FromQuery][Required()]string authorName, [FromQuery][Required()]string authorEmail, [FromBody]List<PatchOperation> patchOperation)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));

            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default(string);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
