/*
 * Tweek
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.KeyUpdateModel;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class KeysApi {
    private ApiClient apiClient;

    public KeysApi() {
        this(Configuration.getDefaultApiClient());
    }

    public KeysApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for createKey
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param keyUpdateModel  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createKeyCall(String keyPath, String authorName, String authorEmail, KeyUpdateModel keyUpdateModel, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = keyUpdateModel;

        // create path and map variables
        String localVarPath = "/keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (keyPath != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("keyPath", keyPath));
        }

        if (authorName != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("author.name", authorName));
        }

        if (authorEmail != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("author.email", authorEmail));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "text/html"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if (progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createKeyValidateBeforeCall(String keyPath, String authorName, String authorEmail, KeyUpdateModel keyUpdateModel, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'keyPath' is set
        if (keyPath == null) {
            throw new ApiException("Missing the required parameter 'keyPath' when calling createKey(Async)");
        }
        
        // verify the required parameter 'authorName' is set
        if (authorName == null) {
            throw new ApiException("Missing the required parameter 'authorName' when calling createKey(Async)");
        }
        
        // verify the required parameter 'authorEmail' is set
        if (authorEmail == null) {
            throw new ApiException("Missing the required parameter 'authorEmail' when calling createKey(Async)");
        }
        
        // verify the required parameter 'keyUpdateModel' is set
        if (keyUpdateModel == null) {
            throw new ApiException("Missing the required parameter 'keyUpdateModel' when calling createKey(Async)");
        }
        

        com.squareup.okhttp.Call call = createKeyCall(keyPath, authorName, authorEmail, keyUpdateModel, progressListener, progressRequestListener);
        return call;

    }

    /**
     * 
     * Save Key
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param keyUpdateModel  (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public String createKey(String keyPath, String authorName, String authorEmail, KeyUpdateModel keyUpdateModel) throws ApiException {
        ApiResponse<String> resp = createKeyWithHttpInfo(keyPath, authorName, authorEmail, keyUpdateModel);
        return resp.getData();
    }

    /**
     * 
     * Save Key
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param keyUpdateModel  (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<String> createKeyWithHttpInfo(String keyPath, String authorName, String authorEmail, KeyUpdateModel keyUpdateModel) throws ApiException {
        com.squareup.okhttp.Call call = createKeyValidateBeforeCall(keyPath, authorName, authorEmail, keyUpdateModel, null, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Save Key
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param keyUpdateModel  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createKeyAsync(String keyPath, String authorName, String authorEmail, KeyUpdateModel keyUpdateModel, final ApiCallback<String> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createKeyValidateBeforeCall(keyPath, authorName, authorEmail, keyUpdateModel, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for keysDeleteKey
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param requestBody  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call keysDeleteKeyCall(String keyPath, String authorName, String authorEmail, List<String> requestBody, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = requestBody;

        // create path and map variables
        String localVarPath = "/keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (keyPath != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("keyPath", keyPath));
        }

        if (authorName != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("author.name", authorName));
        }

        if (authorEmail != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("author.email", authorEmail));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "text/html"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if (progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call keysDeleteKeyValidateBeforeCall(String keyPath, String authorName, String authorEmail, List<String> requestBody, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'keyPath' is set
        if (keyPath == null) {
            throw new ApiException("Missing the required parameter 'keyPath' when calling keysDeleteKey(Async)");
        }
        
        // verify the required parameter 'authorName' is set
        if (authorName == null) {
            throw new ApiException("Missing the required parameter 'authorName' when calling keysDeleteKey(Async)");
        }
        
        // verify the required parameter 'authorEmail' is set
        if (authorEmail == null) {
            throw new ApiException("Missing the required parameter 'authorEmail' when calling keysDeleteKey(Async)");
        }
        

        com.squareup.okhttp.Call call = keysDeleteKeyCall(keyPath, authorName, authorEmail, requestBody, progressListener, progressRequestListener);
        return call;

    }

    /**
     * 
     * 
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param requestBody  (optional)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public String keysDeleteKey(String keyPath, String authorName, String authorEmail, List<String> requestBody) throws ApiException {
        ApiResponse<String> resp = keysDeleteKeyWithHttpInfo(keyPath, authorName, authorEmail, requestBody);
        return resp.getData();
    }

    /**
     * 
     * 
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param requestBody  (optional)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<String> keysDeleteKeyWithHttpInfo(String keyPath, String authorName, String authorEmail, List<String> requestBody) throws ApiException {
        com.squareup.okhttp.Call call = keysDeleteKeyValidateBeforeCall(keyPath, authorName, authorEmail, requestBody, null, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param keyPath  (required)
     * @param authorName  (required)
     * @param authorEmail  (required)
     * @param requestBody  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call keysDeleteKeyAsync(String keyPath, String authorName, String authorEmail, List<String> requestBody, final ApiCallback<String> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = keysDeleteKeyValidateBeforeCall(keyPath, authorName, authorEmail, requestBody, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for keysGetKey
     * @param keyPath  (required)
     * @param revision  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call keysGetKeyCall(String keyPath, String revision, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = new Object();

        // create path and map variables
        String localVarPath = "/keys";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (keyPath != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("keyPath", keyPath));
        }

        if (revision != null) {
            localVarQueryParams.addAll(apiClient.parameterToPair("revision", revision));
        }

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if (progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call keysGetKeyValidateBeforeCall(String keyPath, String revision, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'keyPath' is set
        if (keyPath == null) {
            throw new ApiException("Missing the required parameter 'keyPath' when calling keysGetKey(Async)");
        }
        

        com.squareup.okhttp.Call call = keysGetKeyCall(keyPath, revision, progressListener, progressRequestListener);
        return call;

    }

    /**
     * 
     * 
     * @param keyPath  (required)
     * @param revision  (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Object keysGetKey(String keyPath, String revision) throws ApiException {
        ApiResponse<Object> resp = keysGetKeyWithHttpInfo(keyPath, revision);
        return resp.getData();
    }

    /**
     * 
     * 
     * @param keyPath  (required)
     * @param revision  (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Object> keysGetKeyWithHttpInfo(String keyPath, String revision) throws ApiException {
        com.squareup.okhttp.Call call = keysGetKeyValidateBeforeCall(keyPath, revision, null, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param keyPath  (required)
     * @param revision  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call keysGetKeyAsync(String keyPath, String revision, final ApiCallback<Object> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = keysGetKeyValidateBeforeCall(keyPath, revision, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
