/* 
 * Tweek
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing KeyUpdateModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class KeyUpdateModelTests
    {
        // TODO uncomment below to declare an instance variable for KeyUpdateModel
        //private KeyUpdateModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of KeyUpdateModel
            //instance = new KeyUpdateModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of KeyUpdateModel
        /// </summary>
        [Test]
        public void KeyUpdateModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KeyUpdateModel
            //Assert.IsInstanceOfType<KeyUpdateModel> (instance, "variable 'instance' is a KeyUpdateModel");
        }


        /// <summary>
        /// Test the property 'Implementation'
        /// </summary>
        [Test]
        public void ImplementationTest()
        {
            // TODO unit test for the property 'Implementation'
        }
        /// <summary>
        /// Test the property 'Manifest'
        /// </summary>
        [Test]
        public void ManifestTest()
        {
            // TODO unit test for the property 'Manifest'
        }

    }

}
