export * from './appsApi';
import { AppsApi } from './appsApi';
export * from './configuraitonApi';
import { ConfiguraitonApi } from './configuraitonApi';
export * from './contextApi';
import { ContextApi } from './contextApi';
export * from './dependentApi';
import { DependentApi } from './dependentApi';
export * from './keysApi';
import { KeysApi } from './keysApi';
export * from './manifestApi';
import { ManifestApi } from './manifestApi';
export * from './policyApi';
import { PolicyApi } from './policyApi';
export * from './revisionHistoryApi';
import { RevisionHistoryApi } from './revisionHistoryApi';
export * from './schemaApi';
import { SchemaApi } from './schemaApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './suggestionsApi';
import { SuggestionsApi } from './suggestionsApi';
export * from './tagsApi';
import { TagsApi } from './tagsApi';
export const APIS = [AppsApi, ConfiguraitonApi, ContextApi, DependentApi, KeysApi, ManifestApi, PolicyApi, RevisionHistoryApi, SchemaApi, SearchApi, SuggestionsApi, TagsApi];
