/**
 * Tweek
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import localVarRequest = require('request');
import http = require('http');
import Promise = require('bluebird');

/* tslint:disable:no-unused-locals */
import { PatchOperation } from '../model/patchOperation';

import { ObjectSerializer, Authentication, HttpBasicAuth, ApiKeyAuth, OAuth, VoidAuth } from '../model/models';

let defaultBasePath = 'http://localhost/api/v2';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum SchemaApiApiKeys {
}

export class SchemaApi {
    protected _basePath = defaultBasePath;
    protected defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
    }

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: SchemaApiApiKeys, value: string) {
        (this.authentications as any)[SchemaApiApiKeys[key]].apiKey = value;
    }

    /**
     * Delete Schema
     * @param identityType The type of the identity
     * @param authorName 
     * @param authorEmail 
     */
    public deleteIdentity (identityType: string, authorName: string, authorEmail: string) : Promise<{ response: http.ClientResponse; body: string;  }> {
        const localVarPath = this.basePath + '/schemas/{identityType}'
            .replace('{' + 'identityType' + '}', encodeURIComponent(String(identityType)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'identityType' is not null or undefined
        if (identityType === null || identityType === undefined) {
            throw new Error('Required parameter identityType was null or undefined when calling deleteIdentity.');
        }

        // verify required parameter 'authorName' is not null or undefined
        if (authorName === null || authorName === undefined) {
            throw new Error('Required parameter authorName was null or undefined when calling deleteIdentity.');
        }

        // verify required parameter 'authorEmail' is not null or undefined
        if (authorEmail === null || authorEmail === undefined) {
            throw new Error('Required parameter authorEmail was null or undefined when calling deleteIdentity.');
        }

        if (authorName !== undefined) {
            localVarQueryParameters['author.name'] = ObjectSerializer.serialize(authorName, "string");
        }

        if (authorEmail !== undefined) {
            localVarQueryParameters['author.email'] = ObjectSerializer.serialize(authorEmail, "string");
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: string;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "string");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * Get query
     */
    public getSchemas () : Promise<{ response: http.ClientResponse; body: Array<any>;  }> {
        const localVarPath = this.basePath + '/schemas';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: Array<any>;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "Array<any>");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * Add identity
     * @param identityType 
     * @param authorName 
     * @param authorEmail 
     * @param body 
     */
    public schemaAddIdentity (identityType: string, authorName: string, authorEmail: string, body: any) : Promise<{ response: http.ClientResponse; body: string;  }> {
        const localVarPath = this.basePath + '/schemas/{identityType}'
            .replace('{' + 'identityType' + '}', encodeURIComponent(String(identityType)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'identityType' is not null or undefined
        if (identityType === null || identityType === undefined) {
            throw new Error('Required parameter identityType was null or undefined when calling schemaAddIdentity.');
        }

        // verify required parameter 'authorName' is not null or undefined
        if (authorName === null || authorName === undefined) {
            throw new Error('Required parameter authorName was null or undefined when calling schemaAddIdentity.');
        }

        // verify required parameter 'authorEmail' is not null or undefined
        if (authorEmail === null || authorEmail === undefined) {
            throw new Error('Required parameter authorEmail was null or undefined when calling schemaAddIdentity.');
        }

        // verify required parameter 'body' is not null or undefined
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling schemaAddIdentity.');
        }

        if (authorName !== undefined) {
            localVarQueryParameters['author.name'] = ObjectSerializer.serialize(authorName, "string");
        }

        if (authorEmail !== undefined) {
            localVarQueryParameters['author.email'] = ObjectSerializer.serialize(authorEmail, "string");
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(body, "any")
        };

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: string;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "string");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
    /**
     * Update identity
     * @param identityType 
     * @param authorName 
     * @param authorEmail 
     * @param patchOperation 
     */
    public schemaPatchIdentity (identityType: string, authorName: string, authorEmail: string, patchOperation: Array<PatchOperation>) : Promise<{ response: http.ClientResponse; body: string;  }> {
        const localVarPath = this.basePath + '/schemas/{identityType}'
            .replace('{' + 'identityType' + '}', encodeURIComponent(String(identityType)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

        // verify required parameter 'identityType' is not null or undefined
        if (identityType === null || identityType === undefined) {
            throw new Error('Required parameter identityType was null or undefined when calling schemaPatchIdentity.');
        }

        // verify required parameter 'authorName' is not null or undefined
        if (authorName === null || authorName === undefined) {
            throw new Error('Required parameter authorName was null or undefined when calling schemaPatchIdentity.');
        }

        // verify required parameter 'authorEmail' is not null or undefined
        if (authorEmail === null || authorEmail === undefined) {
            throw new Error('Required parameter authorEmail was null or undefined when calling schemaPatchIdentity.');
        }

        // verify required parameter 'patchOperation' is not null or undefined
        if (patchOperation === null || patchOperation === undefined) {
            throw new Error('Required parameter patchOperation was null or undefined when calling schemaPatchIdentity.');
        }

        if (authorName !== undefined) {
            localVarQueryParameters['author.name'] = ObjectSerializer.serialize(authorName, "string");
        }

        if (authorEmail !== undefined) {
            localVarQueryParameters['author.email'] = ObjectSerializer.serialize(authorEmail, "string");
        }


        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PATCH',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(patchOperation, "Array<PatchOperation>")
        };

        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.ClientResponse; body: string;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "string");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
}
