/* 
 * Tweek
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TagsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TagsApiTests
    {
        private TagsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TagsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TagsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TagsApi
            //Assert.IsInstanceOfType(typeof(TagsApi), instance, "instance is a TagsApi");
        }

        
        /// <summary>
        /// Test SaveTag
        /// </summary>
        [Test]
        public void SaveTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object body = null;
            //instance.SaveTag(body);
            
        }
        
        /// <summary>
        /// Test TagsGet
        /// </summary>
        [Test]
        public void TagsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.TagsGet();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
    }

}
