/*
 * Tweek
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AppCreationRequestModel struct {
	Name string `json:"name"`
	Permissions []string `json:"permissions"`
}
