/*
 * Tweek
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PatchOperation struct {
	Op string `json:"op,omitempty"`
	Path string `json:"path,omitempty"`
	Value map[string]interface{} `json:"value,omitempty"`
}
