/*
 * Tweek
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.PatchOperation;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PolicyApi
 */
@Ignore
public class PolicyApiTest {

    private final PolicyApi api = new PolicyApi();

    
    /**
     * 
     *
     * Get Policies
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPoliciesTest() throws ApiException {
        List<Object> response = api.getPolicies();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Replace Policy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replacePolicyTest() throws ApiException {
        api.replacePolicy();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Update Policy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePolicyTest() throws ApiException {
        List<PatchOperation> patchOperation = null;
        api.updatePolicy(patchOperation);

        // TODO: test validations
    }
    
}
