/*
 * Tweek
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RevisionHistoryApi
 */
@Ignore
public class RevisionHistoryApiTest {

    private final RevisionHistoryApi api = new RevisionHistoryApi();

    
    /**
     * 
     *
     * Get Revision History
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRevisionHistoryTest() throws ApiException {
        String keyPath = null;
        String since = null;
        List<Object> response = api.getRevisionHistory(keyPath, since);

        // TODO: test validations
    }
    
}
