/*
 * Tweek
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagsApi
 */
@Ignore
public class TagsApiTest {

    private final TagsApi api = new TagsApi();

    
    /**
     * 
     *
     * Save tags
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveTagTest() throws ApiException {
        Object body = null;
        api.saveTag(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get all tags
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void tagsGetTest() throws ApiException {
        List<String> response = api.tagsGet();

        // TODO: test validations
    }
    
}
