//
// DependentAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Alamofire



public class DependentAPI: APIBase {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getDependents(completion: ((data: [AnyObject]?, error: ErrorType?) -> Void)) {
        getDependentsWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /dependents
     - Get Dependents     - examples: [{contentType=application/json, example="{}", statusCode=200}]

     - returns: RequestBuilder<[AnyObject]> 
     */
    public class func getDependentsWithRequestBuilder() -> RequestBuilder<[AnyObject]> {
        let path = "/dependents"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[AnyObject]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
