/* 
 * Tweek
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConfiguraitonApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ConfiguraitonApiTests
    {
        private ConfiguraitonApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ConfiguraitonApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConfiguraitonApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ConfiguraitonApi
            //Assert.IsInstanceOfType(typeof(ConfiguraitonApi), instance, "instance is a ConfiguraitonApi");
        }

        
        /// <summary>
        /// Test GetValue
        /// </summary>
        [Test]
        public void GetValueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string keyName = null;
            //List<string> include = null;
            //bool? flatten = null;
            //instance.GetValue(keyName, include, flatten);
            
        }
        
    }

}
