/*
 * Tweek
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContextApi
 */
@Ignore
public class ContextApiTest {

    private final ContextApi api = new ContextApi();

    
    /**
     * 
     *
     * Delete identity context property
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteContextPropTest() throws ApiException {
        String identityType = null;
        String identityId = null;
        String prop = null;
        api.deleteContextProp(identityType, identityId, prop);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Get identity context
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContextTest() throws ApiException {
        String identityType = null;
        String identityId = null;
        api.getContext(identityType, identityId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Save identity context
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveContextTest() throws ApiException {
        String identityType = null;
        String identityId = null;
        api.saveContext(identityType, identityId);

        // TODO: test validations
    }
    
}
