//
// PatchOperation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class PatchOperation: JSONEncodable {
    public var op: String?
    public var path: String?
    public var value: AnyObject?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["op"] = self.op
        nillableDictionary["path"] = self.path
        nillableDictionary["value"] = self.value?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
